apiVersion: apps/v1
kind: Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: keptndemo
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}
  ports:
  - port: 80
    protocol: TCP
    name: flask
  selector:
    app: {{ .Values.appName }}
  type: NodePort
